In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame({'h':[150,160,170,185,190],
                   'w':[50,58,70,80,90]})
df

     h   w
0  150  50
1  160  58
2  170  70
3  185  80
4  190  90

In [3]:
m=df.mean()
# print(m)
s=df.std()
print(s)
z = (df-m)/s
z.round(2)

h    16.733201
w    16.149303
dtype: float64

      h     w
0 -1.25 -1.21
1 -0.66 -0.72
2 -0.06  0.02
3  0.84  0.64
4  1.14  1.26